# Reference: https://build-cpp.github.io/cmkr/cmake-toml

[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr/cmkr.cmake"

[project]
name = "soyuz"
version = "1.1.2"
description = "🚀 Discord RPC Blocker for Lunar Client"
languages = ["CXX", "C"]

[fetch-content]
fmt = { git = "https://github.com/fmtlib/fmt", tag = "8.1.1" }

[target.soyuz]
type = "executable"
sources = ["soyuz/*.cc", "resource/*.rc"]
private-include-directories = ["include/"]
properties = { CMAKE_CXX_EXTENSIONS = false, CXX_STANDARD = "23", CXX_STANDARD_REQUIRED = true, WIN32_EXECUTABLE = true }
compile-options = ["/W4", "/WX"]
private-link-libraries = ["fmt::fmt"]
